server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homit
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB

jwt:
  access:
    secret: 3y8EpfsmbQI4QOkbPniiRQmsm6fAF0ohgO3DI/hFltZbsdJT8MCdE0qSYkm8GdKbqtSTGEYtMPAwEal6yBOWrQ==
  refresh:
    secret: gjGtW+0kPXngmFOr4+5JgagMkEBZnra3WM4UgZt1+b7HbPrT/lOZL1QZZ9KODbPW+OX4YKr8l7hqz01xWITw5g==
